### ISSUE TITLE
Running in non-local mode doesn't work with --no-user

### ISSUE THREAD

**Issue by kvablack** [autognc/ravenML#32]
Trying to run in non-local mode by running a command of the form:
`ravenml train --no-user -d data_1 ...`
or even:
`ravenml train --no-user -d data_1 -l None ...`
gives the error:
`TypeError: expected str, bytes or os.PathLike object, not NoneType`
because raven always attempts to parse the --local parameter into a Path, even if it is None (happens in [this line](https://github.com/autognc/ravenML/blob/04adeac6cdc282a8523dc3d147df700517f1f820/ravenml/train/interfaces.py#L36)).

On another more minor note, if I don't pass the --dataset or --local parameters at all, I get `Error: Invalid value for dataset: bad bad`, which just seems like a bit of a weird error. Also, the documentation for --local is a bit confusing, since it just says "Keep all model artifacts local", which doesn't make it clear that the option actually accepts a string to use as the local path.

**Comment by cSchubes** [comment]
few things on this: 

1. `--no-user` is an option that we want to have, but don't fully support yet because it requires a lot of extra work and we want to prioritize getting models trained at the moment. So just don't use it for now.
2. Good catch on the TypeError though, I intentionally set `local` to None if the argument is 'None' but forget to check in the `TrainInput` function.

Agreed that local is confusing, will try and update
